// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Lookup struct {
	LookupID       uuid.UUID
	TableName      string
	DisplayOrder   int32
	DisplayText    string
	IsActive       bool
	ParentID       uuid.NullUUID
	InternalKey    string
	ConcurrencyKey string
	CreateDate     time.Time
	CreateUserID   int32
	UpdateDate     *time.Time
	UpdateUserID   pgtype.Int4
	ValueText      string
}
